"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useRouter } from 'next/navigation';
import { QueryClient, QueryClientProvider } from 'react-query';
import { useEffect } from "react"
// import Checkauth from '@/components/checkAuthentication';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const router = useRouter()

  useEffect(() => {

    const checkAuth = () => {

      const storedToken = localStorage.getItem("token");
      const storedExpirationDate =localStorage.getItem("expirationDate");

      if (!storedToken || !storedExpirationDate)
        router.push('/login');
      else{
      const expirationDate = new Date(parseInt(storedExpirationDate));
      if (new Date() > expirationDate) {
        localStorage.removeItem("token");
        localStorage.removeItem("expirationDate");
        router.push('/login')
      }

    }}

    // checkAuth();

    const intervalId = setInterval(checkAuth, 20 * 1000);

    return () => {
      clearInterval(intervalId)
    }
  }, [])




  return (
    <html lang="en">
      <body className={inter.className}><QueryClientProvider client={new QueryClient()} >
        {/* <Checkauth > */}

        {children}

        {/* </Checkauth> */}
      </QueryClientProvider></body>
    </html>
  )
}
